services:
  gitea:
    image: fmnx.su/core/gitea:latest
    container_name: gitea
    restart: unless-stopped
    ports:
      - "222:22"
      - "80:3000"
      - "443:3000"
    volumes:
      - ../gitea/data:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    environment:
      APP_NAME: FMNX Project

      DB_TYPE: postgres
      DB_HOST: postgres:5432
      DB_NAME: db
      DB_USER: user
      DB_PASSWD: password

      GITEA__attachment__STORAGE_TYPE: minio
      GITEA__attachment__MAX_SIZE: 1800000

      GITEA__packages__STORAGE_TYPE: minio
      GITEA__packages__MAX_SIZE: 1800000

      GITEA__storage.minio__MINIO_ENDPOINT: minio:9000
      GITEA__storage.minio__MINIO_ACCESS_KEY_ID: 123456
      GITEA__storage.minio__MINIO_SECRET_ACCESS_KEY: 987654321
      GITEA__storage.minio__MINIO_BUCKET: bucket
      GITEA__storage.minio__MINIO_LOCATION: infr
      GITEA__storage.minio__MINIO_USE_SSL: false

      GITEA__ui__THEMES: earl-grey
      GITEA__ui__DEFAULT_THEME: earl-grey

  postgres:
    image: docker.io/postgres:latest
    container_name: postgres
    restart: unless-stopped
    ports:
      - 5432:5432
    volumes:
      - ../postgres/data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: db

  minio:
    image: docker.io/minio/minio:latest
    container_name: minio
    restart: unless-stopped
    command: server /data
    ports:
      - 9000:9000
    volumes:
      - ../minio/data:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    environment:
      MINIO_ACCESS_KEY: 123456
      MINIO_SECRET_KEY: 987654321
