services:
  nginx:
    image: docker.io/nginx:latest
    container_name: nginx
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/nginx.conf:ro
      - ./.lego/certificates:/certs:ro
    depends_on:
      - gitea
      - woodpecker

  gitea:
    image: docker.io/gitea/gitea:latest
    container_name: gitea
    restart: unless-stoppeda
    volumes:
      - ./gitea:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    environment:
      GITEA__ui__THEMES: earl-grey
      GITEA__ui__DEFAULT_THEME: earl-grey
      GITEA__server__APP_DATA_PATH: /data/gitea
      GITEA__server__DOMAIN: fmnx.su
      GITEA__server__SSH_DOMAIN: fmnx.su
      GITEA__server__HTTP_PORT: 80
      GITEA__server__ROOT_URL: https://fmnx.su/
      GITEA__server__LFS_JWT_SECRET: $GITEA__server__LFS_JWT_SECRET
      GITEA__secutrity__INTERNAL_TOKEN: $GITEA__secutrity__INTERNAL_TOKEN
      GITEA__repository__MAX_CREATION_LIMIT: 0
      GITEA__repository__ALLOW_FORK_WITHOUT_MAXIMUM_LIMIT: false
      GITEA__i18n__LANGS: en-US
      GITEA__i18n__NAMES: English
      GITEA__attachment__MAX_SIZE: 1800000

  woodpecker:
    image: docker.io/woodpeckerci/woodpecker-server:latest
    container_name: woodpecker
    restart: unless-stopped
    volumes:
      - ./woodpecker:/var/lib/woodpecker
    environment:
      WOODPECKER_OPEN: true
      WOODPECKER_HOST: https://ci.fmnx.su
      WOODPECKER_AGENT_SECRET: ${WOODPECKER_AGENT_SECRET}
      WOODPECKER_GITEA: true
      WOODPECKER_GITEA_URL: https://fmnx.su
      WOODPECKER_GITEA_CLIENT: ${WOODPECKER_GITEA_CLIENT}
      WOODPECKER_GITEA_SECRET: ${WOODPECKER_GITEA_SECRET}
      WOODPECKER_ADMIN: dancheg97,Dancheg97

  agent:
    image: docker.io/woodpeckerci/woodpecker-agent:latest
    container_name: agent
    restart: unless-stopped
    command: agent
    depends_on:
      - woodpecker
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      WOODPECKER_SERVER: woodpecker:9000
      WOODPECKER_AGENT_SECRET: ${WOODPECKER_AGENT_SECRET}

  mailserver:
    image: docker.io/mailserver/docker-mailserver:latest
    container_name: mailserver
    hostname: mail.fmnx.su
    environment:
      ENABLE_FAIL2BAN: 1
      SSL_TYPE: letsencrypt
      PERMIT_DOCKER: network
      SPOOF_PROTECTION: 0
    volumes:
      - ./mail/mail-data/:/var/mail/
      - ./mail/mail-state/:/var/mail-state/
      - ./mail/mail-logs/:/var/log/mail/
      - ./mail/config/:/tmp/docker-mailserver/
      - ./mail/certbot/certs/:/etc/letsencrypt
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "25:25"
      - "587:587"
      - "465:465"
    cap_add:
      - NET_ADMIN
    restart: always

  repo:
    image: fmnx.su/core/repo
    container_name: repo
    volumes:
      - ./repo:/home/public
    environment:
      REPO_PORT: 80
      REPO_NAME: pk.fmnx.su
      REPO_USERS: user::password user2::password2
      REPO_WORK_DIR: /home
