services:
  nginx:
    image: nginx
    container_name: nginx
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/nginx.conf:ro
      - ./.lego/certificates:/certs:ro
    depends_on:
      - gitea
      - drone
      - kuma

  gitea:
    image: gitea/gitea:1.19
    container_name: gitea
    restart: unless-stopped
    environment:
      GITEA__ui__THEMES: earl-grey
      GITEA__ui__DEFAULT_THEME: earl-grey
      GITEA__server__APP_DATA_PATH: /data/gitea
      GITEA__server__DOMAIN: fmnx.su
      GITEA__server__SSH_DOMAIN: fmnx.su
      GITEA__server__HTTP_PORT: 80
      GITEA__server__ROOT_URL: https://fmnx.su/
      GITEA__repository__MAX_CREATION_LIMIT: 0
      GITEA__repository__ALLOW_FORK_WITHOUT_MAXIMUM_LIMIT: false
      GITEA__i18n__LANGS: en-US
      GITEA__i18n__NAMES: English
      GITEA__attachment__MAX_SIZE: 1800000
    volumes:
      - ./gitea:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro

  drone:
    image: drone/drone
    container_name: drone
    restart: unless-stopped
    env_file:
      - drone/drone.env
    volumes:
      - ./drone:/data
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - gitea

  drone-runner:
    image: drone/drone-runner-docker
    container_name: droner
    restart: unless-stopped
    environment:
      DRONE_RPC_PROTO: http
      DRONE_RPC_HOST: drone
      DRONE_RPC_SECRET: ***REMOVED***
      DRONE_RUNNER_NAME: drone-runner
      DRONE_RUNNER_CAPACITY: 2
      DRONE_RUNNER_NETWORKS: infr_default
      DRONE_DEBUG: false
      DRONE_TRACE: false
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - drone

  mailserver:
    image: docker.io/mailserver/docker-mailserver:latest
    container_name: mailserver
    hostname: mail.fmnx.su
    ports:
      - "25:25"
      - "587:587"
      - "465:465"
    volumes:
      - ./mail/mail-data/:/var/mail/
      - ./mail/mail-state/:/var/mail-state/
      - ./mail/mail-logs/:/var/log/mail/
      - ./mail/config/:/tmp/docker-mailserver/
      - ./mail/certbot/certs/:/etc/letsencrypt
      - /etc/localtime:/etc/localtime:ro
    environment:
      - ENABLE_FAIL2BAN=1
      - SSL_TYPE=letsencrypt
      - PERMIT_DOCKER=network
      - SPOOF_PROTECTION=0
    cap_add:
      - NET_ADMIN
    restart: always

  kuma:
    image: louislam/uptime-kuma:1
    container_name: kuma
    restart: unless-stopped
    volumes:
      - ./kuma:/app/data
  # repo:
  #   image: fmnx.su/core/repo:latest
  #   container_name: repo
  #   env_file:
  #     - repo/repo.env
  #   volumes:
  #     - ./repo/pkg:/var/cache/pacman/pkg
  #   depends_on:
  #     - gitea
