services:
  nginx:
    image: nginx
    container_name: nginx
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/nginx.conf:ro
      - ./.lego/certificates:/certs:ro
    depends_on:
      - gitea
      - drone
      - kuma
      - dozzle
      - docs
      # - repo

  gitea:
    image: gitea/gitea:1.19
    container_name: gitea
    restart: unless-stopped
    environment:
      GITEA__ui__THEMES: earl-grey
      GITEA__ui__DEFAULT_THEME: earl-grey
      GITEA__server__APP_DATA_PATH: /data/gitea
      GITEA__server__DOMAIN: fmnx.io
      GITEA__server__SSH_DOMAIN: fmnx.io
      GITEA__server__HTTP_PORT: 80
      GITEA__server__ROOT_URL: https://fmnx.io/
      GITEA__repository__MAX_CREATION_LIMIT: 0
      GITEA__repository__ALLOW_FORK_WITHOUT_MAXIMUM_LIMIT: false
      GITEA__i18n__LANGS: en-US
      GITEA__i18n__NAMES: English
      GITEA__attachment__MAX_SIZE: 1800000
    volumes:
      - ./gitea:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro

  drone:
    image: drone/drone
    container_name: drone
    restart: unless-stopped
    env_file:
      - drone/drone.env
    volumes:
      - ./drone:/data
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - gitea

  drone-runner:
    image: drone/drone-runner-docker
    container_name: droner
    restart: unless-stopped
    environment:
      DRONE_RPC_PROTO: http
      DRONE_RPC_HOST: drone
      DRONE_RPC_SECRET: ***REMOVED***
      DRONE_RUNNER_NAME: drone-runner
      DRONE_RUNNER_CAPACITY: 2
      DRONE_RUNNER_NETWORKS: composer_default
      DRONE_DEBUG: false
      DRONE_TRACE: false
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - drone

  # repo:
  #   image: fmnx.io/dev/repo:latest
  #   container_name: repo
  #   command: run
  #   env_file:
  #     - repo/repo.env
  #   depends_on:
  #     - gitea

  docs:
    image: squidfunk/mkdocs-material
    container_name: docs
    restart: unless-stopped
    volumes:
      - ./docs:/docs

  tree:
    image: squidfunk/mkdocs-material
    container_name: tree
    restart: unless-stopped
    volumes:
      - ./tree:/docs

  articles:
    image: squidfunk/mkdocs-material
    container_name: articles
    restart: unless-stopped
    volumes:
      - ./articles:/docs

  dozzle:
    image: amir20/dozzle:latest
    container_name: dozzle
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    env_file:
      - dozzle/dozzle.env

  kuma:
    image: louislam/uptime-kuma:1
    container_name: kuma
    restart: unless-stopped
    volumes:
      - ./kuma:/app/data
  # mail:
  #   image: ghcr.io/docker-mailserver/docker-mailserver:latest
  #   container_name: mail
  #   restart: unless-stopped
  #   hostname: mail.fmnx.io
  #   env_file:
  #     - mail/mailserver.env
  #   volumes:
  #     - ./mail/mail-data/:/var/mail/
  #     - ./mail/mail-state/:/var/mail-state/
  #     - ./mail/mail-logs/:/var/log/mail/
  #     - ./mail/config/:/tmp/docker-mailserver/
  #     - /etc/localtime:/etc/localtime:ro
  #   ports:
  #     - "25:25"
  #     - "143:143"
  #     - "465:465"
  #     - "587:587"
  #     - "993:993"
