services:
  nginx:
    image: nginx
    container_name: nginx
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/nginx.conf:ro
      - ./.lego/certificates:/certs:ro
    depends_on:
      - gitea
      - drone
      - kuma

  gitea:
    image: gitea/gitea:1.19
    container_name: gitea
    restart: unless-stopped
    environment:
      GITEA__ui__THEMES: earl-grey
      GITEA__ui__DEFAULT_THEME: earl-grey
      GITEA__server__APP_DATA_PATH: /data/gitea
      GITEA__server__DOMAIN: fmnx.su
      GITEA__server__SSH_DOMAIN: fmnx.su
      GITEA__server__HTTP_PORT: 80
      GITEA__server__ROOT_URL: https://fmnx.su/
      GITEA__repository__MAX_CREATION_LIMIT: 0
      GITEA__repository__ALLOW_FORK_WITHOUT_MAXIMUM_LIMIT: false
      GITEA__i18n__LANGS: en-US
      GITEA__i18n__NAMES: English
      GITEA__attachment__MAX_SIZE: 1800000
    volumes:
      - ./gitea:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro

  drone:
    image: drone/drone
    container_name: drone
    restart: unless-stopped
    environment:
      DRONE_DATABASE_DRIVER: sqlite3
      DRONE_DATABASE_DATASOURCE: /data/database.sqlite
      DRONE_GITEA_SERVER: https://fmnx.su/
      DRONE_GIT_ALWAYS_AUTH: false
      DRONE_SERVER_PROTO: https
      DRONE_SERVER_HOST: ci.fmnx.su
      DRONE_TLS_AUTOCERT: false
      DRONE_RPC_SECRET: $DRONE_RPC_SECRET
      DRONE_USER_CREATE: $DRONE_USER_CREATE
      DRONE_GITEA_CLIENT_ID: $DRONE_GITEA_CLIENT_ID
      DRONE_GITEA_CLIENT_SECRET: $DRONE_GITEA_CLIENT_SECRET
    env_file:
      - drone/drone.env
    volumes:
      - ./drone:/data
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - gitea

  drone-runner:
    image: drone/drone-runner-docker
    container_name: droner
    restart: unless-stopped
    environment:
      DRONE_RPC_PROTO: http
      DRONE_RPC_HOST: drone
      DRONE_RPC_SECRET: $DRONE_RPC_SECRET
      DRONE_RUNNER_NAME: drone-runner
      DRONE_RUNNER_CAPACITY: 2
      DRONE_RUNNER_NETWORKS: infr_default
      DRONE_DEBUG: false
      DRONE_TRACE: false
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - drone

  mailserver:
    image: docker.io/mailserver/docker-mailserver:latest
    container_name: mailserver
    hostname: mail.fmnx.su
    environment:
      ENABLE_FAIL2BAN: 1
      SSL_TYPE: letsencrypt
      PERMIT_DOCKER: network
      SPOOF_PROTECTION: 0
    volumes:
      - ./mail/mail-data/:/var/mail/
      - ./mail/mail-state/:/var/mail-state/
      - ./mail/mail-logs/:/var/log/mail/
      - ./mail/config/:/tmp/docker-mailserver/
      - ./mail/certbot/certs/:/etc/letsencrypt
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "25:25"
      - "587:587"
      - "465:465"
    cap_add:
      - NET_ADMIN
    restart: always

  kuma:
    image: louislam/uptime-kuma:1
    container_name: kuma
    restart: unless-stopped
    volumes:
      - ./kuma:/app/data

  repo:
    image: fmnx.su/core/repo:latest
    container_name: repo
    environment:
      PACKREPO_REPO: pk.fmnx.su
      PACKREPO_API_ADRESS: https://pk.fmnx.su/
      PACKREPO_INIT_PKGS: aur.archlinux.org/gnome-browser-connector aur.archlinux.org/gnome-shell-extension-dash-to-dock aur.archlinux.org/zsh-theme-powerlevel10k-bin-git aur.archlinux.org/zsh-syntax-highlighting-git aur.archlinux.org/adw-gtk3 aur.archlinux.org/visual-studio-code-bin aur.archlinux.org/neovim-git
      PACKREPO_LOGS_FORMAT: text
      PACKREPO_REST: fmnx.su/pkg/adw-gtk-theme fmnx.su/pkg/papirus-icon-theme fmnx.su/core/ainst
      PACKREPO_LOGINS: $PACKREPO_LOGINS
    volumes:
      - ./repo:/var/cache/pacman/pkg
    depends_on:
      - gitea
