services:
  gitea:
    image: fmnx.su/core/gitea:latest
    container_name: gitea
    restart: unless-stopped
    ports:
      - "222:22"
      - "80:3000"
      - "443:3000"
    volumes:
      - ./gitea/data:/data
      - ./.lego/certificates:/certs
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    environment:
      APP_NAME: $APP_NAME

      DB_TYPE: postgres
      DB_HOST: postgres:5432
      DB_NAME: db
      DB_USER: user
      DB_PASSWD: password

      GITEA__server__PROTOCOL: https
      GITEA__server__DOMAIN: $DOMAIN
      GITEA__server__SSH_DOMAIN: $DOMAIN
      GITEA__server__ROOT_URL: https://$DOMAIN/
      GITEA__server__APP_DATA_PATH: /data/gitea
      GITEA__server__CERT_FILE: /certs/$DOMAIN.crt
      GITEA__server__KEY_FILE: /certs/$DOMAIN.key
      GITEA__server__LFS_START_SERVER: true

      GITEA__attachment__STORAGE_TYPE: minio
      GITEA__attachment__MAX_SIZE: 1800000
      GITEA__lfs__STORAGE_TYPE: minio
      GITEA__avatars__STORAGE_TYPE: minio
      GITEA__repo-avatars__STORAGE_TYPE: minio
      GITEA__repo-archive__STORAGE_TYPE: minio
      GITEA__packages__STORAGE_TYPE: minio
      GITEA__packages__MAX_SIZE: 1800000
      GITEA__actions_log__STORAGE_TYPE: minio
      GITEA__actions_artifacts__STORAGE_TYPE: minio

      GITEA__storage.minio__MINIO_ENDPOINT: minio:9000
      GITEA__storage.minio__MINIO_ACCESS_KEY_ID: 123456
      GITEA__storage.minio__MINIO_SECRET_ACCESS_KEY: 987654321
      GITEA__storage.minio__MINIO_BUCKET: bucket
      GITEA__storage.minio__MINIO_LOCATION: infr
      GITEA__storage.minio__MINIO_USE_SSL: false

      GITEA__repository.signing__SIGNING_KEY: default
      GITEA__repository.signing__INITIAL_COMMIT: always
      GITEA__repository.signing__CRUD_ACTIONS: pubkey, twofa, parentsigned
      GITEA__repository.signing__WIKI: never
      GITEA__repository.signing__MERGES: pubkey, twofa, basesigned, commitssigned

      GITEA__ui__THEMES: earl-grey
      GITEA__ui__DEFAULT_THEME: earl-grey

      GITEA__federation__ENABLE: true
      GITEA__federation__MAX_SIZE: 8

      GITEA__service__ENABLE_CAPTCHA: true
      GITEA__service__REGISTER_EMAIL_CONFIRM: true

      GITEA__repository__MAX_CREATION_LIMIT: 100
      GITEA__repository__ALLOW_FORK_WITHOUT_MAXIMUM_LIMIT: false

  postgres:
    image: docker.io/postgres:latest
    container_name: postgres
    restart: unless-stopped
    volumes:
      - ./postgres/data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password

  minio:
    image: docker.io/minio/minio:latest
    container_name: minio
    restart: unless-stopped
    command: server /data
    volumes:
      - ./minio/data:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    environment:
      MINIO_ACCESS_KEY: 123456
      MINIO_SECRET_KEY: 987654321

  mail:
    image: docker.io/mailserver/docker-mailserver:latest
    container_name: mail
    hostname: mail.$DOMAIN
    restart: unless-stopped
    volumes:
      - ./mail/data/mail-data/:/var/mail/
      - ./mail/data/mail-state/:/var/mail-state/
      - ./mail/data/mail-logs/:/var/log/mail/
      - ./mail/data/config/:/tmp/docker-mailserver/
      - ./mail/data/certbot/certs/:/etc/letsencrypt
      - /etc/localtime:/etc/localtime:ro
    cap_add:
      - NET_ADMIN
    ports:
      - "25:25"
      - "587:587"
      - "465:465"
      - "993:993"
    environment:
      ENABLE_FAIL2BAN: 1
      SSL_TYPE: letsencrypt
      PERMIT_DOCKER: network
      SPOOF_PROTECTION: 0
