services:
  nginx:
    image: nginx
    container_name: nginx
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/nginx.conf:ro
      - ./.lego/certificates:/certs:ro
    depends_on:
      - gitea
      - drone
      - pocketbase

  gitea:
    image: gitea/gitea
    container_name: gitea
    restart: unless-stopped
    environment:
      GITEA__ui__THEMES: earl-grey,gitea
      GITEA__ui__DEFAULT_THEME: earl-grey
      GITEA__server__APP_DATA_PATH: /data/gitea
      GITEA__server__DOMAIN: dancheg97.ru
      GITEA__server__SSH_DOMAIN: dancheg97.ru
      GITEA__server__HTTP_PORT: 80
      GITEA__server__ROOT_URL: https://dancheg97.ru/
      GITEA__repository__MAX_CREATION_LIMIT: 0
      GITEA__repository__ALLOW_FORK_WITHOUT_MAXIMUM_LIMIT: false
    volumes:
      - ./gitea:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro

  drone:
    image: drone/drone
    container_name: drone
    restart: unless-stopped
    environment:
      DRONE_DATABASE_DRIVER: sqlite3
      DRONE_DATABASE_DATASOURCE: /data/database.sqlite
      DRONE_GITEA_SERVER: https://dancheg97.ru/
      DRONE_GIT_ALWAYS_AUTH: false
      DRONE_RPC_SECRET: ***REMOVED***
      DRONE_SERVER_PROTO: https
      DRONE_SERVER_HOST: drone.dancheg97.ru
      DRONE_TLS_AUTOCERT: false
      DRONE_USER_CREATE: username:dancheg97,machine:false,admin:true,token:55f24eb3d61ef6ac5e83d550178638dc
      DRONE_GITEA_CLIENT_ID: ***REMOVED***
      DRONE_GITEA_CLIENT_SECRET: ***REMOVED***
    volumes:
      - ./drone:/data
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - gitea

  drone-runner:
    image: drone/drone-runner-docker
    container_name: droner
    restart: unless-stopped
    environment:
      DRONE_RPC_PROTO: http
      DRONE_RPC_HOST: drone
      DRONE_RPC_SECRET: ***REMOVED***
      DRONE_RUNNER_NAME: drone-runner
      DRONE_RUNNER_CAPACITY: 2
      DRONE_RUNNER_NETWORKS: composer_default
      DRONE_DEBUG: false
      DRONE_TRACE: false
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - drone

  pocketbase:
    image: ghcr.io/muchobien/pocketbase
    restart: unless-stopped
    volumes:
      - ./pocketbase:/pb_data
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:8090/api/health || exit 1
      interval: 5s
      timeout: 5s
      retries: 5

  pacman:
    image: dancheg97.ru/dancheg97/go-pacman
    container_name: pacman
    command: run
    volumes:
      - ./go-pacman:/var/cache/pacman/pkg
    environment:
      REPO: pacman.dancheg97.ru
      INIT_PKGS: ttf-droid adw-gtk-theme papirus-icon-theme-git git yay chromium telegram-desktop dconf-editor gnome-calculator gnome-control-center gnome-disk-utility dbus gnome-keyring gnome-logs gnome-system-monitor gnome-shell-extensions xdg-user-dirs-gtk gedit gnome-tweaks docker go python-pip make docker-compose geary drawing gnome-shell-extension-dash-to-dock gnome-shell-extension-gtile visual-studio-code-bin rtw89-dkms-git gnome-browser-connector onlyoffice-bin
    ports:
      - 9080:9080

  docs:
    image: squidfunk/mkdocs-material
    container_name: docs
    volumes:
      - ./mkdocs:/docs

  dozzle:
    container_name: dozzle
    image: amir20/dozzle:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      DOZZLE_USERNAME: dancheg97
      DOZZLE_PASSWORD: dozzlesecretveryhidden

  kuma:
    image: louislam/uptime-kuma:1
    container_name: kuma
    volumes:
      - ./kuma:/app/data
