services:
  gitea:
    image: fmnx.su/core/gitea:latest
    container_name: gitea
    restart: unless-stopped
    ports:
      - "222:22"
      - "80:3000"
      - "443:3000"
    volumes:
      - ./data:/data
      - ./.lego/certificates:/certs
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    environment:
      APP_NAME: FMNX Project

      DB_TYPE: postgres
      DB_HOST: $POSTGRES_HOST
      DB_NAME: $POSTGRES_DB
      DB_USER: $POSTGRES_USER
      DB_PASSWD: $POSTGRES_PASSWORD

      GITEA__server__PROTOCOL: https
      GITEA__server__DOMAIN: $DOMAIN
      GITEA__server__SSH_DOMAIN: $DOMAIN
      GITEA__server__ROOT_URL: https://$DOMAIN/
      GITEA__server__APP_DATA_PATH: /data/gitea
      GITEA__server__CERT_FILE: /certs/$DOMAIN.crt
      GITEA__server__KEY_FILE: /certs/$DOMAIN.key
      GITEA__server__LFS_START_SERVER: true

      GITEA__mailer__ENABLED: true
      GITEA__mailer__FROM: $MAIL_ADDR
      GITEA__mailer__MAILER_TYPE: smtp
      GITEA__mailer__SMTP_ADDR: mail.$DOMAIN
      GITEA__mailer__SMTP_PORT: 587
      GITEA__mailer__USER: $MAIL_ADDR
      GITEA__mailer__PASSWD: $MAIL_PASS

      GITEA__attachment__STORAGE_TYPE: minio
      GITEA__attachment__MAX_SIZE: 1800000
      GITEA__lfs__STORAGE_TYPE: minio
      GITEA__avatars__STORAGE_TYPE: minio
      GITEA__repo-avatars__STORAGE_TYPE: minio
      GITEA__repo-archive__STORAGE_TYPE: minio
      GITEA__packages__STORAGE_TYPE: minio
      GITEA__packages__MAX_SIZE: 1800000
      GITEA__actions_log__STORAGE_TYPE: minio
      GITEA__actions_artifacts__STORAGE_TYPE: minio

      GITEA__storage.minio__MINIO_ENDPOINT: $MINIO_ENDPOINT
      GITEA__storage.minio__MINIO_ACCESS_KEY_ID: $MINIO_ACCESS_KEY_ID
      GITEA__storage.minio__MINIO_SECRET_ACCESS_KEY: $MINIO_SECRET_ACCESS_KEY
      GITEA__storage.minio__MINIO_BUCKET: bucket
      GITEA__storage.minio__MINIO_LOCATION: infr
      GITEA__storage.minio__MINIO_USE_SSL: false

      GITEA__ui__THEMES: earl-grey
      GITEA__ui__DEFAULT_THEME: earl-grey

      GITEA__federation__ENABLE: true
      GITEA__federation__MAX_SIZE: 8

      GITEA__service__ENABLE_CAPTCHA: true
      GITEA__service__REGISTER_EMAIL_CONFIRM: true

      GITEA__repository__MAX_CREATION_LIMIT: 100
      GITEA__repository__ALLOW_FORK_WITHOUT_MAXIMUM_LIMIT: false
