services:
  mail:
    image: docker.io/mailserver/docker-mailserver:latest
    container_name: mail
    hostname: mail.fmnx.su
    restart: unless-stopped
    volumes:
      - ./data/mail-data/:/var/mail/
      - ./data/mail-state/:/var/mail-state/
      - ./data/mail-logs/:/var/log/mail/
      - ./data/config/:/tmp/docker-mailserver/
      - ./data/certbot/certs/:/etc/letsencrypt
      - /etc/localtime:/etc/localtime:ro
    cap_add:
      - NET_ADMIN
    ports:
      - "25:25"
      - "587:587"
      - "465:465"
      - "993:993"
    environment:
      ENABLE_FAIL2BAN: 1
      SSL_TYPE: letsencrypt
      PERMIT_DOCKER: network
      SPOOF_PROTECTION: 0
