services:
  minio:
    image: docker.io/minio/minio:latest
    container_name: minio
    restart: unless-stopped
    command: server /data
    ports:
      - 9000:9000
    volumes:
      - ./data:/data
    environment:
      MINIO_ACCESS_KEY: $MINIO_ACCESS_KEY
      MINIO_SECRET_KEY: $MINIO_SECRET_KEY
