site_name: FMNX Linux distribution

repo_url: https://fmnx.su/
repo_name: fmnx

theme:
  name: material
  logo: assets/logo.png
  favicon: assets/favicon.png

  icon:
    edit: material/pencil
    view: material/eye

  features:
    - content.code.copy
    - announce.dismiss
    - content.action.edit
    - git-revision-date-localized:
      enable_creation_date: true

  palette:
    scheme: slate
    accent: light blue

markdown_extensions:
  - attr_list

plugins:
  - search

extra_css:
  - stylesheets/extra.css
