site_name: Всякий текст

repo_url: https://dancheg97.ru/
repo_name: dancheg97

theme:
  name: material
  logo: assets/logo.png

  icon:
    edit: material/pencil
    view: material/eye

  features:
    - content.code.copy
    - announce.dismiss
    - content.action.edit
    - git-revision-date-localized:
      enable_creation_date: true

  palette:
    scheme: slate
    accent: light blue

plugins:
  - search

extra_css:
  - stylesheets/extra.css
